// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// TreeCDF
NumericVector TreeCDF(SEXP eps, SEXP ds, SEXP Ks, SEXP methods, SEXP mins, SEXP maxs, SEXP grans, SEXP datas);
RcppExport SEXP CDF_PSIdekick_TreeCDF(SEXP epsSEXP, SEXP dsSEXP, SEXP KsSEXP, SEXP methodsSEXP, SEXP minsSEXP, SEXP maxsSEXP, SEXP gransSEXP, SEXP datasSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ds(dsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Ks(KsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type methods(methodsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mins(minsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type maxs(maxsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type grans(gransSEXP);
    Rcpp::traits::input_parameter< SEXP >::type datas(datasSEXP);
    __result = Rcpp::wrap(TreeCDF(eps, ds, Ks, methods, mins, maxs, grans, datas));
    return __result;
END_RCPP
}
// Smooth
NumericVector Smooth(NumericVector x);
RcppExport SEXP CDF_PSIdekick_Smooth(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    __result = Rcpp::wrap(Smooth(x));
    return __result;
END_RCPP
}
